server:
  port: 8083

spring:
  application:
    name: envios-service

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user_logix
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

logging:
  level:
    com.smartlogix.envios: DEBUG