services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - inventario-service
      - pedidos-service
      - envios-service
    networks:
      - smartlogix-network

  inventario-service:
    build:
      context: ./inventario-service
    container_name: inventario-service
    ports:
      - "8081:8081"
    environment:
      # Pasamos las credenciales de tu sistema al contenedor
      - NEON_INVENTARIO_URL=${NEON_INVENTARIO_URL}
      - NEON_INVENTARIO_USER=${NEON_INVENTARIO_USER}
      - NEON_INVENTARIO_PASSWORD=${NEON_INVENTARIO_PASSWORD}
    networks:
      - smartlogix-network

  pedidos-service:
    build:
      context: ./pedidos-service
    container_name: pedidos-service
    ports:
      - "8082:8082"
    environment:
      - NEON_PEDIDOS_URL=${NEON_PEDIDOS_URL}
      - NEON_PEDIDOS_USER=${NEON_PEDIDOS_USER}
      - NEON_PEDIDOS_PASSWORD=${NEON_PEDIDOS_PASSWORD}
      - INVENTARIO_SERVICE_URL=http://inventario-service:8081
    depends_on:
      - inventario-service
    networks:
      - smartlogix-network

  envios-service:
    build:
      context: ./envios-service
    container_name: envios-service
    ports:
      - "8083:8083"
    environment:
      - NEON_ENVIOS_URL=${NEON_ENVIOS_URL}
      - NEON_ENVIOS_USER=${NEON_ENVIOS_USER}
      - NEON_ENVIOS_PASSWORD=${NEON_ENVIOS_PASSWORD}
    networks:
      - smartlogix-network

networks:
  smartlogix-network:
    driver: bridge