server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: inventario-service
            uri: http://inventario-service:8081
            predicates:
              - Path=/api/productos/**, /api/stocks/**

          - id: pedidos-service
            uri: http://pedidos-service:8082
            predicates:
              - Path=/api/pedidos/**

          - id: envios-service
            uri: http://envios-service:8083
            predicates:
              - Path=/api/envios/**

          - id: bff-service
            uri: http://bff-service:8084
            predicates:
              - Path=/api/bff/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG