server:
  port: 8082

spring:
  application:
    name: pedidos-service
  datasource:
    url: jdbc:postgresql://ep-wandering-smoke-aqsjl5o5-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_L6Is0UHhWAQd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

inventario:
  service:
    url: ${INVENTARIO_SERVICE_URL:http://inventario-service:8081}

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
