server:
  port: 8084

spring:
  application:
    name: bff-service

pedidos:
  service:
    url: http://pedidos-service:8082
envios:
  service:
    url: http://envios-service:8083

logging:
  level:
    root: INFO
    com.smartlogix.bff: DEBUG