server:
  port: 8085

spring:
  application:
    name: auth-service

# Configuración de nuestra seguridad JWT
jwt:
  secret: SmartLogixSecretKeyUltraSegura2026ParaDesarrolloLocal
  expiration: 3600000 # 1 hora en milisegundos
