server:
  port: 8081

spring:
  application:
    name: inventario-service

  datasource:
    url: ${NEON_INVENTARIO_URL:jdbc:postgresql://db-inventario:5432/smartlogix_inventario}
    username: ${NEON_INVENTARIO_USER:user_logix}
    password: ${NEON_INVENTARIO_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.smartlogix.inventario: DEBUG
