server:
  port: 8081

spring:
  application:
    name: inventario-service

  datasource:
    # URL corregida con el prefijo jdbc: indispensable para Java
    url: jdbc:postgresql://ep-wandering-smoke-aqsjl5o5-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_L6Is0UHhWAQd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.smartlogix.inventario: DEBUG
